### ISSUE TITLE
[BUG] ```피드 상세 조회 API```에서 author, image 반환 오류 수정 필요

### ISSUE THREAD

**Issue by eunji8784** [TEAM-README/Readme-Server#57]
## Describe the bug
- ```GET /feed/:feedId``` 에서 __author__, __image__ 가 제대로 반환되고 있지 않음.
<img width="229" alt="스크린샷 2022-06-17 오후 12 54 04" src="https://user-images.githubusercontent.com/70746467/174221669-2c15ce6b-d33b-4e40-967a-672c97c2ef21.png">
<img width="230" alt="스크린샷 2022-06-17 오후 12 54 26" src="https://user-images.githubusercontent.com/70746467/174221697-0649911b-6f1d-4424-89ef-6e19c4226103.png">

- author, image가 DB에 저장된 내용과 다르게 나오고 있음
- Book, Feed 엔티티 확인 필요

**Comment by HYOSITIVE** [comment]
나 이거 왜인지 알거같다 내 API 만들다가 뭘 하나 찾아버렸어

**Comment by eunji8784** [comment]
> 나 이거 왜인지 알거같다 내 API 만들다가 뭘 하나 찾아버렸어

오오오오 나는 저거 Feed 엔티티에서 isbn 컬림에 { eager: true } 옵션 설정 안한거랑 타입 string으로 지정해놓은 것 때문이라고 생각했는데, 맞나?!?!

**Comment by HYOSITIVE** [comment]
움 그건 아닌데 반환하는게 APIresponse로 타입 지정이 안되어있더라구? 반환 타입 지정이 안되어있어서 그런게 아닌가 싶은데 내가 지금 대구와있어서 내일 확인해볼겝

**Comment by eunji8784** [comment]
저거 콘솔 로그 찍어보면 아예 테이블 조인이 안되고 있우~ 오키 내일 확인 부탁해~!
